export const getQuoteParams = {
    id: 0 ,
    movement_tab : [],
    movement_uname : [],
    is_start : [],
    stay_price: [] ,
    collection_date : [],
    collection_lat: [] ,
    collection_lng : [],
    collection_address: [],
    destination_lat: [],
    destination_lng: [],
    destination_address: [],
    single: 0 ,
    phone_h : ' ',
    email_h: ' ' ,
    num_id : 0 ,
    car_id : 0 ,
    bag_id : 0 ,
    default_journey_id : 0 ,
    name: ' ' ,
    email : ' ' ,
    phone_m : ' ' ,
    comment: ' ' ,
    creator: -98 ,
    date_require: '0000-00-00' ,
    site_id : ' ' ,
    DONT_UPDATE_MOVEMENT : 0,
    fromApp: true
}   